name: CI-environment-variables

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@env
        with:
          php_version: 8.0
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
          command: config
          args: process-timeout
        env:
          COMPOSER_PROCESS_TIMEOUT: 1
