name: CI-ghcr-io

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@test-tedivm

      - uses: actions/upload-artifact@v2
        with:
          name: debug-output
          path: output.log
