name: CI-version-specific

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check version
        uses: php-actions/composer@79-minor-versions
        with:
          php_version: '8.1'
          version: '2.3.1'
          only_args: --version
