name: CI-version-choice

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use specific version 2.3.1
        uses: php-actions/composer@79-minor-versions
        with:
          php_version: '8.1'
          version: '2.3.1'
          only_args: --version

      - name: Use latest version 2.3
        uses: php-actions/composer@79-minor-versions
        with:
          php_version: '8.1'
          version: '2.3'
          only_args: --version

      - name: Use latest version 2
        uses: php-actions/composer@79-minor-versions
        with:
          php_version: '8.1'
          version: '2'
          only_args: --version
