name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: RedaktionsNetzwerk-Deutschland/composer@bugfix/no-defaults
      - name: Dump autoload
        uses: RedaktionsNetzwerk-Deutschland/composer@bugfix/no-defaults
        with:
          command: dump-autoload
          only_args: --no-dev --no-interaction --classmap-authoritative
