name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy example keys
      - uses: php-actions/composer@private-repo-test
        with:
          ssh_key: ${{ secrets.SSH_KEY }}