name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy example keys
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KEY_PUB: ${{ secrets.SSH_KEY_PUB }}
        run: |
          echo "$SSH_KEY" > ~/.ssh/id_rsa && echo "$SSH_KEY_PUB" > ~/.ssh/id_rsa.pub
      - uses: php-actions/composer@v2