name: Validate

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate dependencies
        uses: php-actions/composer@april-2021-issue
        with:
          command: validate
